spring:
  application:
    name: vgov
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vgov}
    username: ${DB_USERNAME:vgov_user}
    password: ${DB_PASSWORD:vgov_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:your-very-long-secret-key-for-jwt-token-signing}
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: ${SERVER_PORT:8080}

app:
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    base-url: ${FILE_BASE_URL:http://localhost:8080/api/files}
    max-file-size: ${MAX_FILE_SIZE:10MB}
    max-request-size: ${MAX_REQUEST_SIZE:10MB}
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    bucket-name: ${MINIO_BUCKET_NAME:vgov-files}
    secure: ${MINIO_SECURE:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.viettel.vgov: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
