spring:
  application:
    name: vgov

  config:
    import: optional:file:.env[.properties]
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vgov}
    username: ${DB_USERNAME:vgov_user}
    password: ${DB_PASSWORD:vgov_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:sql/seed-data.sql
  
  security:
    jwt:
      secret: ${JWT_SECRET:your-very-long-secret-key-for-jwt-token-signing}
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: ${SERVER_PORT:8080}


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.viettel.vgov: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
